Blog/ViewModels/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Blog.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Логин", Prompt = "Введите логин")]
        public string UserName { get; set; }

        //[Required]
        //[EmailAddress]
        //[Display(Name = "Email", Prompt = "Введите email")]
        //public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить?")]
        public bool RememberMe { get; set; }

       // public string ReturnUrl { get; set; }

    }
}

Blog/ViewModels/Account/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Blog.ViewModels.Account
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Поле Имя обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Имя", Prompt = "Введите имя")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Поле Фамилия обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Фамилия", Prompt = "Введите фамилию")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Поле Email обязательно для заполнения")]
        [EmailAddress]
        [Display(Name = "Email", Prompt = "example@gmail.com")]
        public string EmailReg { get; set; }

        [Required(ErrorMessage = "Поле Пароль обязательно для заполнения")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль")]
        [StringLength(100, ErrorMessage = "Поле {0} должно иметь минимум {2} и максимум {1} символов.", MinimumLength = 5)]
        public string PasswordReg { get; set; }

        [Required(ErrorMessage = "Обязательно подтвердите пароль")]
        [Compare("PasswordReg", ErrorMessage = "Пароли не совпадают")]
        [DataType(DataType.Password)]
        [Display(Name = "Подтвердить пароль", Prompt = "Введите пароль повторно")]
        public string PasswordConfirm { get; set; }

        [Required(ErrorMessage = "Поле Никнейм обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Никнейм", Prompt = "Введите никнейм")]
        public string Login { get; set; }

    }
}

Blog/Controllers/Account/RegisterController.cs
using AutoMapper;
using Blog.Data.Models;
using Blog.ViewModels.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    //[Route("[controller]")]
    public class RegisterController : Controller
    {
        private IMapper _mapper;

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public RegisterController(IMapper mapper, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
        }


        [Route("Register")]
        [HttpGet]
        public IActionResult Register()
        {
            return View("Register");
        }

        [Route("Register")]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<User>(model);

                var result = await _userManager.CreateAsync(user, model.PasswordReg);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View("Register", model);
        }


    }
}

Blog/Controllers/RolesController.cs
using AutoMapper;
using Blog.Contracts.Models.Roles;
using Blog.Data.Models;
using Blog.Data.Repos;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    [Route("[controller]")]
    public class RolesController : Controller
    {
        private IRoleRepository _roles;
        private IMapper _mapper;

        public RolesController(
            IRoleRepository roles,
            IMapper mapper)
        {
            _roles = roles;
            _mapper = mapper;
        }


        /// <summary>
        /// view list Roles
        /// </summary>
        [HttpGet]
        [Route("AllRoles")]
        public async Task<IActionResult> GetRoles()
        {
            var roles = await _roles.GetAllRoles();

            var response = new GetRolesResponse
            {              
                RolesAmount = roles.Length,
                Roles = _mapper.Map<Role[], RoleView[]>(roles)
            };

            return View(response);
        }

  
    }
}

Blog/Controllers/UsersController.cs
using AutoMapper;
using Blog.Contracts.Models.Users;
using Blog.Data.Models;
using Blog.Data.Queries;
using Blog.Data.Repos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Authentication;
using System.Security.Claims;

namespace Blog.Controllers
{
    [Route("[controller]")]
    public class UsersController : Controller
    {
        private IMapper _mapper;
        private IUserRepository _users;

        public UsersController(
            IMapper mapper,
            IUserRepository users)
        {
            _mapper = mapper;
            _users = users;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public IActionResult AllUsers()
        //{
        //    return View();
        //}

        /// <summary>
        /// view all users 
        /// </summary>
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        [Route("AllUsers")]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _users.GetUsers();

            var response = new GetUsersResponse
            {
                Users = _mapper.Map<User[], UsersView[]>(users)
            };

            return View(response);
        }



        //[HttpPost]
        //[Route("authenticate")]
        //public async Task<IActionResult> Authenticate(string email, string password)
        //{
        //    if (String.IsNullOrEmpty(email) || String.IsNullOrEmpty(password))
        //        throw new ArgumentNullException("Данные введены не корректно");

        //    User user = await _users.GetUserByEmail(email);

        //    if (user is null)
        //        throw new AuthenticationException("Пользователь на найден");

        //    if (user.Password != password)
        //        throw new AuthenticationException("Введенный пароль не корректен");

        //    // т.к. у пользователя может быть не одна роль а клайм роли принимает строку вторым аргументом
        //    // переделаем список ролей в строку где через запятую перечислены все роли.
        //    string userRoles = string.Join(",", user.Roles.Select(n => n.Name).ToArray());

        //    var claims = new List<Claim>
        //    {
        //        new Claim(ClaimsIdentity.DefaultNameClaimType, user.Email),
        //        new Claim(ClaimsIdentity.DefaultRoleClaimType, userRoles)
        //    };

        //    ClaimsIdentity claimsIdentity = new ClaimsIdentity(
        //        claims,
        //        "AppCookie",
        //        ClaimsIdentity.DefaultNameClaimType,
        //        ClaimsIdentity.DefaultRoleClaimType);

        //    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

        //    var response = new GetUserResponse
        //    {
        //        User = _mapper.Map<User, UserView>(user)
        //    };

        //    return StatusCode(200, response);
        //}


        /// <summary>
        /// view user by id
        /// </summary>
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> GetUserById([FromRoute] string id)
        {
            var user = await _users.GetUser(id);

            if (user is null)
                return StatusCode(400, $"Ошибка! User c id:{id} не найден!");

            var response = new GetUserResponse
            {
                User = _mapper.Map<User, UserView>(user)
            };

            return StatusCode(200, response);
        }


        /// <summary>
        /// update user
        /// </summary>
        [HttpPut]
        [Route("{id}")]
        public async Task<IActionResult> UpdateUser(
            [FromRoute] string id,
            [FromBody] UpdateUserRequest request)
        {
            var user = await _users.GetUser(id);

            if (user is null)
                return StatusCode(400, $"Ошибка! User c id:{id} не найден!");

            await _users.UpdateUser(
               user,
               new UpdateUserQuery(
               request.Email,
               request.Password,
               request.FirstName,
               request.LastName,
               request.DisplayName
               ));

            return StatusCode(201, $"Пост {id} успешно изменен.");
        }

        /// <summary>
        /// add user
        /// </summary>
        [HttpPost]
        [Route("Add")]
        public async Task<IActionResult> AddUser([FromBody] AddUserRequest request)
        {
            var user = _mapper.Map<AddUserRequest, User>(request);

            await _users.RegisterUser(user);

            return StatusCode(201, $"Пользователь: {user.FirstName} {user.LastName} успешно зарегистрирован!");
        }

        /// <summary>
        /// deleting user by id
        /// </summary>
        [HttpDelete]
        [Route("{id}")]
        public async Task<IActionResult> DeleteUser([FromRoute] string id)
        {
            var user = await _users.GetUser(id);

            if (user is null)
                return StatusCode(400, $"Ошибка удаления пользователя. Пользователь c id: {id} не найден!");

            await _users.DeleteUser(user);

            return StatusCode(200, $"Пользователь {user.FirstName} {user.LastName} :: {user.Id} успешно удален!");
        }
    }
}

Blog/Views/Shared/Login.cshtml
@model Blog.ViewModels.Account.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<form method="post" asp-controller="AccountManager" asp-action="Login">
    <fieldset>
            
        <div class="container">
            <main  role="main" class="pb-3">
                <h3>Welcome to the Blog!</h3>
                <!-- <legend></legend> -->
               
                <div class="form-group">
                    <label class="form-label mt-4">Use your Account</label>
                    <div class="form-floating mb-3">
                        <input asp-for="UserName" type="text" class="form-control" id="floatingInputUserName" placeholder="UserName">
                        <label for="floatingInputUserName">UserName</label>
                       @* <span asp-validation-for="UserName" class="text-danger"></span>*@
                    </div>
                    <div class="form-floating  mb-3">
                        <input asp-for="Password" type="password" value="" class="form-control" id="floatingPassword" placeholder="Password">
                        <label for="floatingPassword">Password</label>
                        @*<div class="invalid-feedback">sorry, wrong password. try another?</div>*@
                    </div>
                       
                    <div class="row">
                        <div class="col-lg-2">
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </div>

                         <div class="col-lg-7" style="padding-left: 43%;">
                            <p class="text-primary">New to this Blog?</p>                                                   
                        </div>

                        <div class="col-lg-3">
                            @Html.RouteLink("Create acccount", new { action = "Register", controller="Register"}, new { @class="text-info"} )
                        </div>                                    
                    </div>


                </div>
             
                <!-- <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    <h4 class="alert-heading">Warning!</h4>
                    <p>- Lorem ipsum dolor sit amet conse ctetur, adipisicing elit.</p>
                </div> -->

                <!-- <div class="form-group has-success">
                    <label class="form-label mt-4" for="inputvalid">valid input</label>
                    <input type="text" value="correct value" class="form-control is-valid" id="inputvalid">
                    <div class="valid-feedback">success! you've done it.</div>
                </div>
                <div class="form-group has-danger">
                    <label class="form-label mt-4" for="inputinvalid">invalid input</label>
                    <input type="text" value="wrong value" class="form-control is-invalid" id="inputinvalid">
                    <div class="invalid-feedback">sorry, that username's taken. try another?</div>
                </div> -->
                    
            </main>                                         
        </div>          
    </fieldset>
</form>
 




 
  
                    
    

Blog/Views/Shared/Register.cshtml
@model Blog.ViewModels.Account.RegisterViewModel

@{
    ViewData["Title"] = "Register";
}

<form method="post" asp-controller="Register" asp-action="Register">
    <!-- style="padding: 7% 35% 0%;" -->
    <fieldset>
            
        <div class="container">
            <!-- style="padding-top: 10%;" -->
            <main  role="main" class="pb-3">

                <legend>Register user</legend>

                <div class="form-group">    

                   
                        
                    <div class="row">
                        <div class="form-floating mb-3 col-lg-6">
                            <input asp-for="FirstName" type="text" class="form-control" id="floatingInputFirstName" placeholder="write your First Name">
                            <label for="floatingInputFirstName">First Name</label>
                            <span asp-validation-for="FirstName"></span>
                           @* <small id="emailHelp" class="form-text text-muted">Minimum length is 8 characters.</small>*@
                        </div>
                        <div class="form-floating mb-3 col-lg-6">
                            <input asp-for="LastName" type="text" class="form-control" id="floatingInputLastName" placeholder="write your Last Name">
                            <label for="floatingInputLastName">Last Name</label>
                            <span asp-validation-for="LastName"></span>
                        </div>
                    </div>
                        
                    <div class="form-floating mb-3">
                        <input asp-for="Login" type="text" class="form-control" id="floatingInputLogin" placeholder="User Name">
                        <label for="floatingInputLogin">User Name</label>
                         <span asp-validation-for="Login"></span>
                        @*<small id="UserNamelHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
                    </div>
                    <div class="form-floating mb-3">
                        <input asp-for="EmailReg" type="email"  class="form-control"  id="floatingInputEmail" placeholder="name@example.com">
                        <label for="floatingInputEmail">Email address</label>
                        <span asp-validation-for="EmailReg"></span>
                       @* <div class="valid-feedback">such email is free</div>*@
                    </div>
                    <div class="form-floating mb-3">
                        <input asp-for="PasswordReg" type="password" class="form-control" id="floatingInputPassword" placeholder="Password">
                        <label for="floatingInputPassword">Password</label>
                         <span asp-validation-for="PasswordReg"></span>
                       @* <div class="invalid-feedback">sorry, wrong password. try another?</div>*@
                    </div>
                        <div class="form-floating mb-3">
                        <input asp-for="PasswordConfirm" type="password" class="form-control" id="floatingInputPasswordConfirm" placeholder="PasswordConfirm">
                        <label for="floatingInputPasswordConfirm">Password confirm</label>
                         <span asp-validation-for="PasswordConfirm"></span>
                       @* <div class="invalid-feedback">sorry, wrong password. try another?</div>*@
                    </div>

                     <div asp-validation-summary="ModelOnly"></div>

                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                    <div class="col-lg-9" style="padding-left: 52%;">
                        <p class="text-primary">Already have login and password?</p>                                                   
                    </div>
                    <div class="col-lg-1">
                            <p>                           
                             @Html.RouteLink("Sign In", new { action = "Index", controller="Home"}, new { @class="text-info"} )
                            </p>
                    </div>   

                </div>
                        
                </div>

            </main>                                         
        </div> 
    </fieldset>
</form>


@*<h2>Регистрация нового пользователя</h2>
<form method="post" asp-controller="Register" asp-action="Register">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="FirstName"></label><br />
        <input asp-for="FirstName" />
        <span asp-validation-for="FirstName"></span>
    </div>
    <div>
        <label asp-for="LastName"></label><br />
        <input asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>
    <div>
        <label asp-for="Login"></label><br />
        <input asp-for="Login" />
        <span asp-validation-for="Login"></span>
    </div>
    <div>
        <label asp-for="EmailReg"></label><br />
        <input asp-for="EmailReg" />
        <span asp-validation-for="EmailReg"></span>
    </div>
    <div>
        <label asp-for="PasswordReg"></label><br />
        <input asp-for="PasswordReg" />
        <span asp-validation-for="PasswordReg"></span>
    </div>
    <div>
        <label asp-for="PasswordConfirm"></label><br />
        <input asp-for="PasswordConfirm" />
        <span asp-validation-for="PasswordConfirm"></span>
    </div>
    <div>
        <input type="submit" value="Регистрация" />
    </div>
</form>*@

Blog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using Blog.Data.Models;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager;

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/style/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blog.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                 
                 @if (!SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>                  
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyBlog</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03"
                        aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                       <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link"  asp-controller="Home" asp-action="SignIn">Sign In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  asp-controller="Home" asp-action="RegisterUser">Register User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  asp-controller="Users" asp-action="AllUsers">All Users</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link"  asp-controller="Roles" asp-action="AllRoles">All Roles</a>
                        </li> 

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                     
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>


                    <partial name="_LoginPartial.cshtml" />
                  @*  <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                    </div>
                }

                
             
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bootstrap.Examples - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>